version: "2"
services:
  driver:
    build:
      context: src/driver
    volumes:
      - ./src/driver/:/scripts
    environment:
      - EXPERIMENT_CONFIG=deploy_config_test.json
  workloadgenerator:
    build:
      context: src/workloadgenerator
    volumes:
      - ./src/workloadgenerator/:/app
