AWSTemplateFormatVersion: 2010-09-09
Description: An API that proxies requests to another HTTP endpoint
Parameters:
  LambdaArn:
    Type: String
  GeotBenchId:
    Type: String  

Resources:
  Api:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref GeotBenchId
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: !Sub
        - Api for Geot Bench for ${Name}
        - { Name: !Ref GeotBenchId }

  Resource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt Api.RootResourceId
      RestApiId: !Ref Api
      PathPart: !Ref GeotBenchId
  RootMethod:
    DependsOn:
            - Api
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      ApiKeyRequired: true
      HttpMethod: ANY
      ResourceId: !GetAtt Api.RootResourceId
      RestApiId: !Ref Api 
      Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          PassthroughBehavior: WHEN_NO_MATCH
          Uri: !Join ["", ["arn:aws:apigateway:", !Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaArn, "/invocations"] ]

  ProxyMethod:
      DependsOn:
          - RootMethod
      Type: 'AWS::ApiGateway::Method'
      Properties:
        ApiKeyRequired: true
        HttpMethod: ANY
        ResourceId: !Ref Resource
        RestApiId: !Ref Api
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: !Join ["", ["arn:aws:apigateway:", !Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaArn, "/invocations"] ]
          PassthroughBehavior: WHEN_NO_MATCH
  FunctionPermissions:
    Type: "AWS::Lambda::Permission"
    Properties: 
      Action: "lambda:InvokeFunction"        
      FunctionName: !Ref LambdaArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Join [ "", ["arn:aws:execute-api:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", !Ref Api, "/*" ] ] 

  Deployment:
    DependsOn:
      - RootMethod
      - ProxyMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref Api
      StageName: prod

  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn:
      - Deployment
    Properties:
      Name:  !Sub
        - geotbench-api-key-${Name}
        - { Name: !Ref GeotBenchId }
      Description: CloudFormation API Key V1
      Enabled: 'true'
      StageKeys:
        - RestApiId: !Ref Api
          StageName: prod
  UsagePlan:
    DependsOn:
      - Deployment
      - Api 
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref Api
          Stage: prod
      Description: Default UP
      UsagePlanName: !Sub
        - ${Name}-UsagePlan
        - { Name: !Ref GeotBenchId }
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn: 
      - UsagePlan
      - ApiKey
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
